package org.byters.ldjam39.model;

public enum InteractEnum {
    GET_HAMMER,
    GET_MONEY,
    GO_TO_OUTDOOR,
    GET_FISHING_ROD,
    GO_TO_HOME,
    GO_TO_PARK,
    GO_TO_MARKET,
    RETURN_TO_OUTDOOR,
    RETURN_TO_PARK_FROM_MARKET,
    GET_CAT_FOOD,
    BUY_IN_MARKET,
    FILL_CAT_DISH,
    GET_SHOVEL,
    FIX_BENCH,
    GO_TO_FOREST,
    RETURN_TO_PARK_FROM_FOREST,
    GET_WORMS,
    CATCH_FISH,
    GET_TREE,
    PLANT_TREE,
    GET_FLOWERS,
    GIVE_NANCY_A_GIFT,
    NONE
}
