package org.byters.ldjam39.model;

public enum WorldItemsEnum {
    HAMMER,
    FISHING_ROD,
    CAT_DISH_EMPTY,
    CAT_DISH_FULL,
    MONEY,
    SIGN_PARK,
    MARKET_DOOR,
    CAT_FOOD_IN_MARKET,
    SELLER,
    SHOVEL,
    BENCH_FIXED,
    BENCH_BROKEN,
    FOREST_PORTAL,
    WORMS,
    POUND,
    FOREST_TREE,
    TREE_IN_OUTDOOR,
    TREE_HOLE_IN_OUTDOOR,
    MODAL_IMAGE_SELFIE_AVAILABLE,
    MODAL_IMAGE_SELFIE_SHOW,
    FLOWERS_IN_MARKET,
    NANCY_CALL, HOME_DOOR
}
